name: Generate weather articles

on:
  schedule:
    # ИЗМЕНЕНО: Новое расписание
    # UTC: 03:30 → Рига: 06:30 (летом, UTC+3)
    - cron: '30 3 * * *'
    # UTC: 15:30 → Рига: 18:30 (летом, UTC+3)
    - cron: '30 15 * * *'
  # Позволяет запускать воркфлоу вручную из вкладки Actions на GitHub
  workflow_dispatch:

# 1) Даём экшену право записывать (commit) файлы в репозиторий
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Скачиваем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Нужна полная история для коммитов

      # Шаг 2: Настраиваем среду Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Ускоряет установку

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # Шаг 4: Определяем, утро сейчас или вечер в Риге
      - name: Determine time of day (Riga)
        id: tod
        run: |
          HOUR=$(TZ=Europe/Riga date +'%H')
          if [ "$HOUR" -ge 16 ]; then
            echo "TIME_OF_DAY=evening" >> $GITHUB_ENV
          else
            echo "TIME_OF_DAY=morning" >> $GITHUB_ENV
          fi
          echo "It is $HOUR:00 in Riga → ${{ env.TIME_OF_DAY }}"

      # Шаг 5: Запускаем скрипт генерации статьи
      - name: Generate article
        run: node generate-article.js "${{ env.TIME_OF_DAY }}"
        env:
          # Передаём в скрипт время суток и секретный API-ключ
          TIME_OF_DAY: ${{ env.TIME_OF_DAY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # Шаг 6: (Необязательно) Проверяем, что файлы были созданы
      - name: List generated files
        run: |
          echo "::group::git status"
          git status --porcelain
          echo "::endgroup::"
          echo "::group::ls -la"
          ls -la
          echo "::endgroup::"

      # Шаг 7: Сохраняем сгенерированные файлы в репозиторий
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          # Указываем, какие файлы добавлять в коммит
          add: |
            article-*.json
            latest-article.json
          # Сообщение для коммита
          message: "Auto-update weather article (${{ env.TIME_OF_DAY }})"
          # Автор коммита
          default_author: github_actions
          # Автоматически отправляем коммит в репозиторий
          push: true
